version: "3.9"

services:
  frontend:
    build: /var/www/frontend
    ports:
      - "${FRONTEND_PORT}:80"
    container_name: frontend

  backend:
    build: /var/www/backend
    ports:
      - "${BACKEND_PORT}:8080"
    container_name: backend

  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/db:/var/lib/postgresql/data
    container_name: database

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

  pktriot:
    container_name: tunnel
    image: packetriot/pktriot:latest
    restart: unless-stopped
    volumes:
      - ./pktriot:/data
